// Generated by seal.
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>

#ifndef NULL
#define NULL ((void*)0)
#endif

#include "stdio.h"
#include "stdlib.h"

void * malloc(size_t size);
void free(void * ptr);
int printf(const char * format, ...);
int main(void);

int main(void) {
	void * ptr = malloc(64);
	printf("%s %d\n", "allocated", 64);
	free(ptr);
	return 0;
}

