// Generated by seal.
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>

#ifndef NULL
#define NULL ((void*)0)
#endif

typedef struct Vec2 {
	float x;
	float y;
} Vec2;

float LengthSq(Vec2 v);
int main(void);

float LengthSq(Vec2 v) {
	return (((v).x * (v).x) + ((v).y * (v).y));
}

int main(void) {
	Vec2 v = (Vec2){.x = 3.0, .y = 4.0};
	float result = LengthSq(v);
	printf("%f", result);
	return 0;
}

