// Generated by seal.
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>

#ifndef NULL
#define NULL ((void*)0)
#endif

typedef struct Vec2 {
	float x;
	float y;
} Vec2;

Vec2 Vec2Add(Vec2 a, Vec2 b);
int main(void);

Vec2 Vec2Add(Vec2 a, Vec2 b) {
	Vec2 __seal_return_value_0 = (Vec2){.x = ((a).x + (b).x), .y = ((a).y + (b).y)};
	return __seal_return_value_0;
}

int main(void) {
	Vec2 a = (Vec2){.x = 1.0, .y = 2.0};
	Vec2 b = (Vec2){.x = 3.0, .y = 4.0};
	Vec2 c = Vec2Add(a, b);
	printf("%f", (c).x);
	return 0;
}

