// Generated by seal.
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>

#ifndef NULL
#define NULL ((void*)0)
#endif

typedef struct Circle {
	float radius;
} Circle;

typedef struct Rectangle {
	float width;
	float height;
} Rectangle;

typedef enum Shape_Tag {
	Shape_Tag_nil = 0,
	Shape_Tag_Circle,
	Shape_Tag_Rectangle
} Shape_Tag;

typedef struct Shape {
	Shape_Tag tag;
	union {
		Circle Circle;
		Rectangle Rectangle;
	} as;
} Shape;

float Area(Shape s);
int main(void);

float Area(Shape s) {
	Shape __seal_union_switch_0 = s;
	switch (__seal_union_switch_0.tag) {
		case Shape_Tag_Circle:
			{
				Circle shape = __seal_union_switch_0.as.Circle;
				float __seal_return_value_1 = ((shape).radius * (shape).radius);
				return __seal_return_value_1;
				break;
			}
		case Shape_Tag_Rectangle:
			{
				Rectangle shape = __seal_union_switch_0.as.Rectangle;
				float __seal_return_value_2 = ((shape).width * (shape).height);
				return __seal_return_value_2;
				break;
			}
		case Shape_Tag_nil:
			{
				void *shape = NULL;
				float __seal_return_value_3 = 0;
				return __seal_return_value_3;
				break;
			}
	}
	float __seal_return_value_4 = 0;
	return __seal_return_value_4;
}

int main(void) {
	Shape s = (Shape){.tag = Shape_Tag_Circle, .as.Circle = (Circle){.radius = 5.0}};
	printf("%f", Area(s));
	return 0;
}

