// Generated by seal.
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>

#ifndef NULL
#define NULL ((void*)0)
#endif

typedef enum sealTypeKind {
	sealType_invalid = 0,
	sealType_bool,
	sealType_int,
	sealType_usize,
	sealType_f32,
	sealType_f64,
	sealType_string,
	sealType_rawptr,
	sealType_any
} sealTypeKind;

typedef struct sealAny {
	sealTypeKind type;
	union {
		bool as_bool;
		int as_int;
		size_t as_usize;
		float as_f32;
		double as_f64;
		const char *as_string;
		void *as_rawptr;
	} value;
} sealAny;

static inline sealAny sealAny_bool(bool value) { sealAny out; out.type = sealType_bool; out.value.as_bool = value; return out; }
static inline sealAny sealAny_int(int value) { sealAny out; out.type = sealType_int; out.value.as_int = value; return out; }
static inline sealAny sealAny_usize(size_t value) { sealAny out; out.type = sealType_usize; out.value.as_usize = value; return out; }
static inline sealAny sealAny_f32(float value) { sealAny out; out.type = sealType_f32; out.value.as_f32 = value; return out; }
static inline sealAny sealAny_f64(double value) { sealAny out; out.type = sealType_f64; out.value.as_f64 = value; return out; }
static inline sealAny sealAny_string(const char *value) { sealAny out; out.type = sealType_string; out.value.as_string = value; return out; }
static inline sealAny sealAny_rawptr(void *value) { sealAny out; out.type = sealType_rawptr; out.value.as_rawptr = value; return out; }
static inline sealAny sealAny_any(sealAny value) { return value; }

typedef struct sealVariadic_bool {
	bool *data;
	size_t len;
} sealVariadic_bool;
typedef struct sealVariadic_int {
	int *data;
	size_t len;
} sealVariadic_int;
typedef struct sealVariadic_usize {
	size_t *data;
	size_t len;
} sealVariadic_usize;
typedef struct sealVariadic_f32 {
	float *data;
	size_t len;
} sealVariadic_f32;
typedef struct sealVariadic_f64 {
	double *data;
	size_t len;
} sealVariadic_f64;
typedef struct sealVariadic_string {
	const char * *data;
	size_t len;
} sealVariadic_string;
typedef struct sealVariadic_rawptr {
	void * *data;
	size_t len;
} sealVariadic_rawptr;
typedef struct sealVariadic_any {
	sealAny *data;
	size_t len;
} sealVariadic_any;

int Sum(sealVariadic_int args);
int CountAny(sealVariadic_any args);
int main(void);

int Sum(sealVariadic_int args) {
	int total = 0;
	for (int i = 0; (i < (int)((args).len)); i = (i + 1)) {
		total = (total + (args).data[i]);
	}
	int __seal_return_value_0 = total;
	return __seal_return_value_0;
}

int CountAny(sealVariadic_any args) {
	int __seal_return_value_1 = (int)((args).len);
	return __seal_return_value_1;
}

int main(void) {
	sealAny x = sealAny_int(10);
	printf("%d", Sum((sealVariadic_int){.data = (int[]){1, 2, 3}, .len = 3}));
	printf("%d", CountAny((sealVariadic_any){.data = (sealAny[]){x, sealAny_string("hello"), sealAny_f64(3.14)}, .len = 3}));
	return 0;
}

