package cgen

import (
	"fmt"
	"strings"

	"seal/internal/ast"
	"seal/internal/diag"
	"seal/internal/source"
	"seal/internal/token"
)

type CType struct {
	Name     string
	SealName string

	IsArray  bool
	ArrayLen string
	Elem     *CType
}

func (t CType) String() string {
	if t.IsArray && t.Elem != nil {
		return fmt.Sprintf("[%s]%s", t.ArrayLen, t.Elem.String())
	}

	return t.Name
}

func (t CType) Decl(name string) string {
	if t.IsArray && t.Elem != nil {
		return fmt.Sprintf("%s %s[%s]", t.Elem.Name, name, t.ArrayLen)
	}

	return fmt.Sprintf("%s %s", t.Name, name)
}

var (
	CInvalid = CType{Name: "/*invalid*/ int", SealName: "<invalid>"}
	CVoid    = CType{Name: "void", SealName: "void"}
	CBool    = CType{Name: "bool", SealName: "bool"}
	CInt     = CType{Name: "int", SealName: "int"}
	CF32     = CType{Name: "float", SealName: "f32"}
	CF64     = CType{Name: "double", SealName: "f64"}
	CString  = CType{Name: "const char *", SealName: "string"}
	CNil     = CType{Name: "void *", SealName: "nil"}
)

type valueInfo struct {
	Type CType
}

type scope struct {
	parent *scope
	vars   map[string]valueInfo
}

func newScope(parent *scope) *scope {
	return &scope{
		parent: parent,
		vars:   map[string]valueInfo{},
	}
}

func (s *scope) declare(name string, typ CType) {
	s.vars[name] = valueInfo{Type: typ}
}

func (s *scope) lookup(name string) (valueInfo, bool) {
	for current := s; current != nil; current = current.parent {
		if v, ok := current.vars[name]; ok {
			return v, true
		}
	}

	return valueInfo{}, false
}

type taskInfo struct {
	Decl       *ast.TaskDecl
	ReturnType CType
	ParamTypes []CType
}

type Generator struct {
	diags *diag.Reporter

	out    strings.Builder
	indent int

	structs map[string]*ast.StructDecl
	enums   map[string]*ast.EnumDecl
	tasks   map[string]taskInfo
	consts  map[string]CType

	scope *scope

	currentTask    *ast.TaskDecl
	currentResults []CType
}

func New(diags *diag.Reporter) *Generator {
	return &Generator{
		diags:   diags,
		structs: map[string]*ast.StructDecl{},
		enums:   map[string]*ast.EnumDecl{},
		tasks:   map[string]taskInfo{},
		consts:  map[string]CType{},
	}
}

func (g *Generator) Generate(file *ast.File) string {
	g.collect(file)

	g.line("// Generated by seal.")
	g.line("#include <stdbool.h>")
	g.line("#include <stdint.h>")
	g.line("#include <stddef.h>")
	g.line("#include <stdio.h>")
	g.line("")
	g.line("#ifndef NULL")
	g.line("#define NULL ((void*)0)")
	g.line("#endif")
	g.line("")

	g.emitEnums(file)
	g.emitStructs(file)
	g.emitConstants(file)
	g.emitTaskPrototypes(file)
	g.emitTasks(file)

	return g.out.String()
}

func (g *Generator) collect(file *ast.File) {
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.StructDecl:
			g.structs[d.Name.Name] = d

		case *ast.EnumDecl:
			g.enums[d.Name.Name] = d

		case *ast.TaskDecl:
			if d.IsTest {
				continue
			}

			info := taskInfo{
				Decl: d,
			}

			if len(d.Results) == 0 {
				if d.Name.Name == "Main" {
					info.ReturnType = CInt
				} else {
					info.ReturnType = CVoid
				}
			} else if len(d.Results) == 1 {
				info.ReturnType = g.cTypeFromAst(d.Results[0])
			} else {
				g.error(d.Span(), fmt.Sprintf("task %q has multiple returns; C codegen does not support this yet", d.Name.Name))
				info.ReturnType = CInvalid
			}

			for _, param := range d.Params {
				info.ParamTypes = append(info.ParamTypes, g.cTypeFromAst(param.Type))
			}

			g.tasks[d.Name.Name] = info

		case *ast.ConstDecl:
			g.consts[d.Name.Name] = g.inferExprType(d.Value, nil)
		}
	}
}

func (g *Generator) emitEnums(file *ast.File) {
	for _, decl := range file.Decls {
		d, ok := decl.(*ast.EnumDecl)
		if !ok {
			continue
		}

		g.linef("typedef enum %s {", d.Name.Name)
		g.indent++

		for i, variant := range d.Variants {
			comma := ","
			if i == len(d.Variants)-1 {
				comma = ""
			}

			g.linef("%s_%s%s", d.Name.Name, variant.Name, comma)
		}

		g.indent--
		g.linef("} %s;", d.Name.Name)
		g.line("")
	}
}

func (g *Generator) emitStructs(file *ast.File) {
	for _, decl := range file.Decls {
		d, ok := decl.(*ast.StructDecl)
		if !ok {
			continue
		}

		if len(d.Params) > 0 {
			g.error(d.Name.Span(), fmt.Sprintf("generic struct %q is not supported by C codegen yet", d.Name.Name))
			continue
		}

		g.linef("typedef struct %s {", d.Name.Name)
		g.indent++

		for _, field := range d.Fields {
			fieldType := g.cTypeFromAst(field.Type)
			g.linef("%s;", fieldType.Decl(field.Name.Name))
		}

		g.indent--
		g.linef("} %s;", d.Name.Name)
		g.line("")
	}
}

func (g *Generator) emitConstants(file *ast.File) {
	for _, decl := range file.Decls {
		d, ok := decl.(*ast.ConstDecl)
		if !ok {
			continue
		}

		typ := g.inferExprType(d.Value, nil)
		value := g.emitExpr(d.Value, &typ)
		g.linef("static const %s = %s;", typ.Decl(d.Name.Name), value)
	}

	if len(g.consts) > 0 {
		g.line("")
	}
}

func (g *Generator) emitTaskPrototypes(file *ast.File) {
	for _, decl := range file.Decls {
		d, ok := decl.(*ast.TaskDecl)
		if !ok || d.IsTest {
			continue
		}

		g.linef("%s;", g.taskSignature(d, false))
	}

	if len(g.tasks) > 0 {
		g.line("")
	}
}

func (g *Generator) emitTasks(file *ast.File) {
	for _, decl := range file.Decls {
		d, ok := decl.(*ast.TaskDecl)
		if !ok || d.IsTest {
			continue
		}

		g.emitTask(d)
		g.line("")
	}
}

func (g *Generator) emitTask(d *ast.TaskDecl) {
	info := g.tasks[d.Name.Name]

	g.currentTask = d
	g.currentResults = nil

	if len(d.Results) == 1 {
		g.currentResults = append(g.currentResults, g.cTypeFromAst(d.Results[0]))
	}

	g.linef("%s {", g.taskSignature(d, true))
	g.indent++

	oldScope := g.scope
	g.scope = newScope(oldScope)

	for i, param := range d.Params {
		if i < len(info.ParamTypes) {
			g.scope.declare(param.Name.Name, info.ParamTypes[i])
		}
	}

	g.emitBlockStatements(d.Body)

	if d.Name.Name == "Main" && len(d.Results) == 0 {
		g.line("return 0;")
	}

	g.scope = oldScope

	g.indent--
	g.line("}")

	g.currentTask = nil
	g.currentResults = nil
}

func (g *Generator) taskSignature(d *ast.TaskDecl, definition bool) string {
	info := g.tasks[d.Name.Name]

	name := g.cTaskName(d.Name.Name)
	ret := info.ReturnType.Name

	if len(d.Params) == 0 {
		return fmt.Sprintf("%s %s(void)", ret, name)
	}

	var params []string

	for i, param := range d.Params {
		paramType := CInvalid
		if i < len(info.ParamTypes) {
			paramType = info.ParamTypes[i]
		}

		params = append(params, paramType.Decl(param.Name.Name))
	}

	return fmt.Sprintf("%s %s(%s)", ret, name, strings.Join(params, ", "))
}

func (g *Generator) cTaskName(name string) string {
	if name == "Main" {
		return "main"
	}

	return name
}

func (g *Generator) emitBlockStatements(block *ast.BlockStmt) {
	if block == nil {
		return
	}

	for _, stmt := range block.Stmts {
		g.emitStmt(stmt)
	}
}

func (g *Generator) emitStmt(stmt ast.Stmt) {
	switch s := stmt.(type) {
	case *ast.DeclStmt:
		g.error(s.Span(), "local declarations are not supported by C codegen yet")

	case *ast.BlockStmt:
		g.line("{")
		g.indent++

		oldScope := g.scope
		g.scope = newScope(oldScope)
		g.emitBlockStatements(s)
		g.scope = oldScope

		g.indent--
		g.line("}")

	case *ast.ReturnStmt:
		g.emitReturnStmt(s)

	case *ast.DeferStmt:
		g.error(s.Span(), "defer is not supported by C codegen yet")

	case *ast.SealStmt:
		// `seal` is a checker/language rule. It has no first-backend C output.

	case *ast.ExprStmt:
		g.linef("%s;", g.emitExpr(s.Expr, nil))

	case *ast.AssignStmt:
		left := g.emitExpr(s.Left, nil)
		right := g.emitExpr(s.Right, nil)
		g.linef("%s %s %s;", left, g.cAssignOp(s.Op), right)

	case *ast.VarDeclStmt:
		g.emitVarDeclStmt(s)

	case *ast.IfStmt:
		cond := g.emitExpr(s.Cond, &CBool)
		g.linef("if (%s) {", cond)
		g.indent++

		oldScope := g.scope
		g.scope = newScope(oldScope)
		g.emitBlockStatements(s.Then)
		g.scope = oldScope

		g.indent--

		if s.Else != nil {
			g.line("} else {")
			g.indent++

			oldScope := g.scope
			g.scope = newScope(oldScope)
			g.emitStmt(s.Else)
			g.scope = oldScope

			g.indent--
			g.line("}")
		} else {
			g.line("}")
		}

	case *ast.ForStmt:
		g.emitForStmt(s)

	case *ast.SwitchStmt:
		g.emitSwitchStmt(s)
	}
}

func (g *Generator) emitReturnStmt(s *ast.ReturnStmt) {
	if len(s.Values) == 0 {
		if g.currentTask != nil && g.currentTask.Name.Name == "Main" {
			g.line("return 0;")
			return
		}

		g.line("return;")
		return
	}

	expected := (*CType)(nil)
	if len(g.currentResults) == 1 {
		expected = &g.currentResults[0]
	}

	g.linef("return %s;", g.emitExpr(s.Values[0], expected))
}

func (g *Generator) emitVarDeclStmt(s *ast.VarDeclStmt) {
	var typ CType

	if s.HasType {
		typ = g.cTypeFromAst(s.Type)

		if typ.IsArray && typ.ArrayLen == "" && s.HasValue {
			if arr, ok := s.Value.(*ast.ArrayLiteralExpr); ok {
				typ.ArrayLen = fmt.Sprintf("%d", len(arr.Values))
			}
		}
	} else if s.HasValue {
		typ = g.inferExprType(s.Value, nil)
	} else {
		typ = CInvalid
	}

	g.scope.declare(s.Name.Name, typ)

	if s.HasValue {
		value := g.emitExpr(s.Value, &typ)

		if typ.IsArray {
			g.linef("%s = %s;", typ.Decl(s.Name.Name), value)
		} else {
			g.linef("%s = %s;", typ.Decl(s.Name.Name), value)
		}

		return
	}

	g.linef("%s;", typ.Decl(s.Name.Name))
}

func (g *Generator) emitForStmt(s *ast.ForStmt) {
	oldScope := g.scope
	g.scope = newScope(oldScope)

	if s.Init == nil && s.Cond == nil && s.Post == nil {
		g.line("for (;;) {")
		g.indent++
		g.emitBlockStatements(s.Body)
		g.indent--
		g.line("}")
		g.scope = oldScope
		return
	}

	if s.Init == nil && s.Post == nil {
		cond := g.emitExpr(s.Cond, &CBool)
		g.linef("for (; %s; ) {", cond)
		g.indent++
		g.emitBlockStatements(s.Body)
		g.indent--
		g.line("}")
		g.scope = oldScope
		return
	}

	init := ""
	if s.Init != nil {
		init = g.emitForPart(s.Init)
	}

	cond := ""
	if s.Cond != nil {
		cond = g.emitExpr(s.Cond, &CBool)
	}

	post := ""
	if s.Post != nil {
		post = g.emitForPart(s.Post)
	}

	g.linef("for (%s; %s; %s) {", init, cond, post)
	g.indent++
	g.emitBlockStatements(s.Body)
	g.indent--
	g.line("}")

	g.scope = oldScope
}

func (g *Generator) emitForPart(stmt ast.Stmt) string {
	switch s := stmt.(type) {
	case *ast.VarDeclStmt:
		var typ CType

		if s.HasType {
			typ = g.cTypeFromAst(s.Type)
		} else if s.HasValue {
			typ = g.inferExprType(s.Value, nil)
		} else {
			typ = CInvalid
		}

		g.scope.declare(s.Name.Name, typ)

		if s.HasValue {
			value := g.emitExpr(s.Value, &typ)
			return fmt.Sprintf("%s = %s", typ.Decl(s.Name.Name), value)
		}

		return typ.Decl(s.Name.Name)

	case *ast.AssignStmt:
		return fmt.Sprintf("%s %s %s", g.emitExpr(s.Left, nil), g.cAssignOp(s.Op), g.emitExpr(s.Right, nil))

	case *ast.ExprStmt:
		return g.emitExpr(s.Expr, nil)

	default:
		g.error(stmt.Span(), "unsupported for-loop component in C codegen")
		return ""
	}
}

func (g *Generator) emitSwitchStmt(s *ast.SwitchStmt) {
	if s.IsUnionSwitch {
		g.error(s.Span(), "union switch is not supported by C codegen yet")
		return
	}

	targetType := g.inferExprType(s.Target, nil)
	target := g.emitExpr(s.Target, nil)

	g.linef("switch (%s) {", target)
	g.indent++

	for _, swCase := range s.Cases {
		switch swCase.Kind {
		case ast.SwitchCaseEnumVariant:
			g.linef("case %s_%s:", targetType.SealName, swCase.EnumVariant.Name)

		case ast.SwitchCaseDefault:
			g.line("default:")

		case ast.SwitchCaseExpr:
			g.linef("case %s:", g.emitExpr(swCase.Expr, &targetType))

		default:
			g.error(swCase.Loc, "unsupported switch case in C codegen")
			continue
		}

		g.indent++

		oldScope := g.scope
		g.scope = newScope(oldScope)

		for _, stmt := range swCase.Body {
			g.emitStmt(stmt)
		}

		g.line("break;")

		g.scope = oldScope

		g.indent--
	}

	g.indent--
	g.line("}")
}

func (g *Generator) emitExpr(expr ast.Expr, expected *CType) string {
	switch e := expr.(type) {
	case *ast.IdentExpr:
		if _, ok := g.scope.lookup(e.Name.Name); ok {
			return e.Name.Name
		}

		return e.Name.Name

	case *ast.DotIdentExpr:
		if expected != nil && expected.SealName != "" {
			if _, ok := g.enums[expected.SealName]; ok {
				return fmt.Sprintf("%s_%s", expected.SealName, e.Name.Name)
			}
		}

		g.error(e.Span(), fmt.Sprintf("enum literal .%s needs C codegen context", e.Name.Name))
		return "0"

	case *ast.IntLitExpr:
		return e.Value

	case *ast.FloatLitExpr:
		return e.Value

	case *ast.StringLitExpr:
		return e.Value

	case *ast.BoolLitExpr:
		if e.Value {
			return "true"
		}

		return "false"

	case *ast.NilLitExpr:
		return "NULL"

	case *ast.UnaryExpr:
		return fmt.Sprintf("(%s%s)", g.cUnaryOp(e.Op), g.emitExpr(e.Expr, nil))

	case *ast.BinaryExpr:
		left := g.emitExpr(e.Left, nil)
		right := g.emitExpr(e.Right, nil)
		return fmt.Sprintf("(%s %s %s)", left, g.cBinaryOp(e.Op), right)

	case *ast.CallExpr:
		return g.emitCallExpr(e)

	case *ast.SelectorExpr:
		left := g.emitExpr(e.Left, nil)
		leftType := g.inferExprType(e.Left, nil)

		if strings.HasSuffix(leftType.SealName, "*") {
			return fmt.Sprintf("(%s)->%s", left, e.Name.Name)
		}

		if strings.HasPrefix(leftType.SealName, "*") {
			return fmt.Sprintf("(%s)->%s", left, e.Name.Name)
		}

		return fmt.Sprintf("(%s).%s", left, e.Name.Name)

	case *ast.IndexExpr:
		return fmt.Sprintf("%s[%s]", g.emitExpr(e.Left, nil), g.emitExpr(e.Index, &CInt))

	case *ast.ArrayLiteralExpr:
		var values []string

		elemExpected := (*CType)(nil)
		if expected != nil && expected.IsArray && expected.Elem != nil {
			elemExpected = expected.Elem
		}

		for _, value := range e.Values {
			values = append(values, g.emitExpr(value, elemExpected))
		}

		return "{" + strings.Join(values, ", ") + "}"

	case *ast.CompoundLiteralExpr:
		typ := g.cTypeFromAst(e.Type)
		var values []string

		for _, field := range e.Fields {
			fieldType := g.lookupStructFieldType(typ.SealName, field.Name.Name)
			values = append(values, fmt.Sprintf(".%s = %s", field.Name.Name, g.emitExpr(field.Value, &fieldType)))
		}

		for _, value := range e.Values {
			values = append(values, g.emitExpr(value, nil))
		}

		return fmt.Sprintf("(%s){%s}", typ.Name, strings.Join(values, ", "))
	}

	g.error(expr.Span(), "unsupported expression in C codegen")
	return "0"
}

func (g *Generator) emitCallExpr(e *ast.CallExpr) string {
	if id, ok := e.Callee.(*ast.IdentExpr); ok {
		if id.Name.Name == "Print" {
			return g.emitBuiltinPrint(e)
		}

		name := g.cTaskName(id.Name.Name)
		info, hasTask := g.tasks[id.Name.Name]

		var args []string
		for i, arg := range e.Args {
			expected := (*CType)(nil)
			if hasTask && i < len(info.ParamTypes) {
				expected = &info.ParamTypes[i]
			}

			args = append(args, g.emitExpr(arg, expected))
		}

		return fmt.Sprintf("%s(%s)", name, strings.Join(args, ", "))
	}

	var args []string
	for _, arg := range e.Args {
		args = append(args, g.emitExpr(arg, nil))
	}

	return fmt.Sprintf("%s(%s)", g.emitExpr(e.Callee, nil), strings.Join(args, ", "))
}

func (g *Generator) emitBuiltinPrint(e *ast.CallExpr) string {
	if len(e.Args) == 0 {
		return `printf("")`
	}

	var format strings.Builder
	var args []string

	for _, arg := range e.Args {
		argType := g.inferExprType(arg, nil)

		switch argType.SealName {
		case "int":
			format.WriteString("%d")
			args = append(args, g.emitExpr(arg, nil))

		case "f32", "f64":
			format.WriteString("%f")
			args = append(args, g.emitExpr(arg, nil))

		case "bool":
			format.WriteString("%s")
			args = append(args, fmt.Sprintf("(%s ? \"true\" : \"false\")", g.emitExpr(arg, nil)))

		case "string":
			format.WriteString("%s")
			args = append(args, g.emitExpr(arg, nil))

		default:
			g.error(arg.Span(), fmt.Sprintf("Print does not support %s in C codegen yet", argType.String()))
		}
	}

	if len(args) == 0 {
		return fmt.Sprintf("printf(\"%s\")", escapeCString(format.String()))
	}

	return fmt.Sprintf("printf(\"%s\", %s)", escapeCString(format.String()), strings.Join(args, ", "))
}

func (g *Generator) inferExprType(expr ast.Expr, expected *CType) CType {
	switch e := expr.(type) {
	case *ast.IdentExpr:
		if v, ok := g.scope.lookup(e.Name.Name); ok {
			return v.Type
		}

		if typ, ok := g.consts[e.Name.Name]; ok {
			return typ
		}

		if info, ok := g.tasks[e.Name.Name]; ok {
			return info.ReturnType
		}

		return CInvalid

	case *ast.DotIdentExpr:
		if expected != nil {
			return *expected
		}

		return CInvalid

	case *ast.IntLitExpr:
		return CInt

	case *ast.FloatLitExpr:
		if expected != nil && expected.SealName == "f32" {
			return CF32
		}

		return CF64

	case *ast.StringLitExpr:
		return CString

	case *ast.BoolLitExpr:
		return CBool

	case *ast.NilLitExpr:
		return CNil

	case *ast.UnaryExpr:
		inner := g.inferExprType(e.Expr, nil)

		switch e.Op {
		case token.Amp:
			return CType{
				Name:     inner.Name + " *",
				SealName: "*" + inner.SealName,
			}

		case token.Star:
			if strings.HasPrefix(inner.SealName, "*") {
				return CType{
					Name:     strings.TrimSuffix(strings.TrimSpace(inner.Name), "*"),
					SealName: strings.TrimPrefix(inner.SealName, "*"),
				}
			}
		}

		return inner

	case *ast.BinaryExpr:
		switch e.Op {
		case token.EqEq,
			token.NotEq,
			token.Lt,
			token.LtEq,
			token.Gt,
			token.GtEq,
			token.AndAnd,
			token.OrOr:
			return CBool
		}

		left := g.inferExprType(e.Left, nil)
		right := g.inferExprType(e.Right, nil)

		if left.SealName == "f64" || right.SealName == "f64" {
			return CF64
		}

		if left.SealName == "f32" || right.SealName == "f32" {
			return CF32
		}

		return left

	case *ast.CallExpr:
		if id, ok := e.Callee.(*ast.IdentExpr); ok {
			if info, ok := g.tasks[id.Name.Name]; ok {
				return info.ReturnType
			}
		}

		return CInvalid

	case *ast.SelectorExpr:
		leftType := g.inferExprType(e.Left, nil)
		sealName := strings.TrimPrefix(leftType.SealName, "*")
		return g.lookupStructFieldType(sealName, e.Name.Name)

	case *ast.IndexExpr:
		leftType := g.inferExprType(e.Left, nil)
		if leftType.IsArray && leftType.Elem != nil {
			return *leftType.Elem
		}

		return CInvalid

	case *ast.ArrayLiteralExpr:
		elem := CInvalid

		if len(e.Values) > 0 {
			elem = g.inferExprType(e.Values[0], nil)
		}

		return CType{
			IsArray:  true,
			ArrayLen: fmt.Sprintf("%d", len(e.Values)),
			Elem:     &elem,
			Name:     elem.Name,
			SealName: "array",
		}

	case *ast.CompoundLiteralExpr:
		return g.cTypeFromAst(e.Type)
	}

	return CInvalid
}

func (g *Generator) cTypeFromAst(t ast.Type) CType {
	switch typ := t.(type) {
	case *ast.NamedType:
		if len(typ.Parts) == 0 {
			return CInvalid
		}

		name := typ.Parts[len(typ.Parts)-1].Name

		switch name {
		case "void":
			return CVoid
		case "bool":
			return CBool
		case "int":
			return CInt
		case "f32":
			return CF32
		case "f64":
			return CF64
		case "string":
			return CString
		default:
			return CType{Name: name, SealName: name}
		}

	case *ast.PointerType:
		elem := g.cTypeFromAst(typ.Elem)

		return CType{
			Name:     elem.Name + " *",
			SealName: "*" + elem.SealName,
		}

	case *ast.ArrayType:
		elem := g.cTypeFromAst(typ.Elem)
		length := ""

		if typ.Inferred {
			length = ""
		} else if typ.Len != nil {
			if lit, ok := typ.Len.(*ast.IntLitExpr); ok {
				length = lit.Value
			} else {
				length = g.emitExpr(typ.Len, &CInt)
			}
		}

		return CType{
			IsArray:  true,
			ArrayLen: length,
			Elem:     &elem,
			Name:     elem.Name,
			SealName: "[" + length + "]" + elem.SealName,
		}

	case *ast.GenericType:
		g.error(typ.Span(), "generic type instantiation is not supported by C codegen yet")
		return g.cTypeFromAst(typ.Base)
	}

	return CInvalid
}

func (g *Generator) lookupStructFieldType(structName string, fieldName string) CType {
	d := g.structs[structName]
	if d == nil {
		return CInvalid
	}

	for _, field := range d.Fields {
		if field.Name.Name == fieldName {
			return g.cTypeFromAst(field.Type)
		}
	}

	return CInvalid
}

func (g *Generator) cAssignOp(op token.Kind) string {
	switch op {
	case token.Assign:
		return "="
	case token.PlusEq:
		return "+="
	case token.MinusEq:
		return "-="
	case token.StarEq:
		return "*="
	case token.SlashEq:
		return "/="
	case token.PercentEq:
		return "%="
	default:
		return "="
	}
}

func (g *Generator) cUnaryOp(op token.Kind) string {
	switch op {
	case token.Minus:
		return "-"
	case token.Bang:
		return "!"
	case token.Tilde:
		return "~"
	case token.Amp:
		return "&"
	case token.Star:
		return "*"
	default:
		return ""
	}
}

func (g *Generator) cBinaryOp(op token.Kind) string {
	switch op {
	case token.Plus:
		return "+"
	case token.Minus:
		return "-"
	case token.Star:
		return "*"
	case token.Slash:
		return "/"
	case token.Percent:
		return "%"
	case token.EqEq:
		return "=="
	case token.NotEq:
		return "!="
	case token.Lt:
		return "<"
	case token.LtEq:
		return "<="
	case token.Gt:
		return ">"
	case token.GtEq:
		return ">="
	case token.AndAnd:
		return "&&"
	case token.OrOr:
		return "||"
	case token.Amp:
		return "&"
	case token.Pipe:
		return "|"
	case token.Caret:
		return "^"
	default:
		return "/*op*/"
	}
}

func (g *Generator) line(s string) {
	g.out.WriteString(strings.Repeat("\t", g.indent))
	g.out.WriteString(s)
	g.out.WriteByte('\n')
}

func (g *Generator) linef(format string, args ...any) {
	g.line(fmt.Sprintf(format, args...))
}

func (g *Generator) error(span source.Span, message string) {
	g.diags.Add(span, message)
}

func escapeCString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	return s
}
