package cgen

import (
	"fmt"
	"sort"
	"strings"

	"seal/internal/ast"
	"seal/internal/diag"
	"seal/internal/source"
	"seal/internal/token"
)

type CType struct {
	Name     string
	SealName string

	IsArray    bool
	IsVariadic bool
	ArrayLen   string
	Elem       *CType
}

func (t CType) String() string {
	if t.IsVariadic && t.Elem != nil {
		return "..." + t.Elem.String()
	}

	if t.IsArray && t.Elem != nil {
		return fmt.Sprintf("[%s]%s", t.ArrayLen, t.Elem.String())
	}

	return t.Name
}

func (t CType) Decl(name string) string {
	if t.IsArray && t.Elem != nil {
		return fmt.Sprintf("%s %s[%s]", t.Elem.Name, name, t.ArrayLen)
	}

	return fmt.Sprintf("%s %s", t.Name, name)
}

var (
	CInvalid = CType{Name: "/*invalid*/ int", SealName: "<invalid>"}
	CVoid    = CType{Name: "void", SealName: "void"}
	CBool    = CType{Name: "bool", SealName: "bool"}
	CInt     = CType{Name: "int", SealName: "int"}
	CF32     = CType{Name: "float", SealName: "f32"}
	CF64     = CType{Name: "double", SealName: "f64"}
	CUsize   = CType{Name: "size_t", SealName: "usize"}
	CRawptr  = CType{Name: "void *", SealName: "rawptr"}
	CAny     = CType{Name: "sealAny", SealName: "any"}
	CString  = CType{Name: "const char *", SealName: "string"}
	CNil     = CType{Name: "void *", SealName: "nil"}
)

type valueInfo struct {
	Type CType
}

type scope struct {
	parent *scope
	vars   map[string]valueInfo
	defers []string
}

func newScope(parent *scope) *scope {
	return &scope{
		parent: parent,
		vars:   map[string]valueInfo{},
	}
}

func (s *scope) addDefer(code string) {
	s.defers = append(s.defers, code)
}

func (s *scope) declare(name string, typ CType) {
	s.vars[name] = valueInfo{Type: typ}
}

func (s *scope) lookup(name string) (valueInfo, bool) {
	for current := s; current != nil; current = current.parent {
		if v, ok := current.vars[name]; ok {
			return v, true
		}
	}

	return valueInfo{}, false
}

type TaskInfo struct {
	Decl       *ast.TaskDecl
	ReturnType CType
	ParamTypes []CType

	RequiredParams  int
	ParamDefaults   []ast.Expr
	ParamHasDefault []bool
	ParamIsVariadic []bool
	IsVariadic      bool

	IsExtern   bool
	ExternName string
}

type PackageInfo struct {
	Name      string
	Tasks     map[string]TaskInfo
	Overloads map[string][]string
}

type Generator struct {
	diags *diag.Reporter

	out    strings.Builder
	indent int

	packageName string
	packages    map[string]*PackageInfo

	structs   map[string]*ast.StructDecl
	enums     map[string]*ast.EnumDecl
	unions    map[string]*ast.UnionDecl
	tasks     map[string]TaskInfo
	overloads map[string][]string
	consts    map[string]CType

	scope     *scope
	taskScope *scope

	currentTask    *ast.TaskDecl
	currentResults []CType

	tempCounter int
}

func New(diags *diag.Reporter) *Generator {
	return NewWithPackages(diags, "", nil)
}

func NewWithPackages(diags *diag.Reporter, packageName string, packages map[string]*PackageInfo) *Generator {
	return &Generator{
		diags:       diags,
		packageName: packageName,
		packages:    packages,
		structs:     map[string]*ast.StructDecl{},
		enums:       map[string]*ast.EnumDecl{},
		unions:      map[string]*ast.UnionDecl{},
		tasks:       map[string]TaskInfo{},
		overloads:   map[string][]string{},
		consts:      map[string]CType{},
	}
}

func ExportPackageInfo(packageName string, file *ast.File, reporter *diag.Reporter) *PackageInfo {
	g := NewWithPackages(reporter, packageName, nil)
	g.collect(file)

	return &PackageInfo{
		Name:      packageName,
		Tasks:     g.tasks,
		Overloads: g.overloads,
	}
}

func (g *Generator) newTemp(prefix string) string {
	name := fmt.Sprintf("__seal_%s_%d", prefix, g.tempCounter)
	g.tempCounter++
	return name
}

func (g *Generator) Generate(file *ast.File) string {
	g.collect(file)

	g.line("// Generated by seal.")
	g.line("#include <stdbool.h>")
	g.line("#include <stdint.h>")
	g.line("#include <stddef.h>")
	g.line("#include <stdio.h>")
	g.line("")
	g.line("#ifndef NULL")
	g.line("#define NULL ((void*)0)")
	g.line("#endif")
	g.line("")

	g.emitCImports(file)
	g.emitRuntimeSupport()
	g.emitEnums(file)
	g.emitStructs(file)
	g.emitUnions(file)
	g.emitConstants(file)
	g.emitImportedTaskPrototypes()
	g.emitTaskPrototypes(file)
	g.emitTasks(file)

	return g.out.String()
}

func (g *Generator) collect(file *ast.File) {
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.StructDecl:
			g.structs[d.Name.Name] = d

		case *ast.EnumDecl:
			g.enums[d.Name.Name] = d

		case *ast.UnionDecl:
			g.unions[d.Name.Name] = d

		case *ast.OverloadDecl:
			for _, name := range d.Names {
				g.overloads[d.Name] = append(g.overloads[d.Name], name.Name)
			}

		case *ast.TaskDecl:
			if d.IsTest {
				continue
			}

			info := TaskInfo{
				Decl:           d,
				RequiredParams: len(d.Params),
				IsExtern:       d.IsExtern,
				ExternName:     d.ExternName,
			}

			if len(d.Results) == 0 {
				if d.Name.Name == "Main" {
					info.ReturnType = CInt
				} else {
					info.ReturnType = CVoid
				}
			} else if len(d.Results) == 1 {
				info.ReturnType = g.cTypeFromAst(d.Results[0])
			} else {
				g.error(d.Span(), fmt.Sprintf("task %q has multiple returns; C codegen does not support this yet", d.Name.Name))
				info.ReturnType = CInvalid
			}

			for i, param := range d.Params {
				info.ParamTypes = append(info.ParamTypes, g.cTypeFromAst(param.Type))
				info.ParamDefaults = append(info.ParamDefaults, param.Default)
				info.ParamHasDefault = append(info.ParamHasDefault, param.HasDefault)
				info.ParamIsVariadic = append(info.ParamIsVariadic, param.IsVariadic)

				if param.IsVariadic {
					info.IsVariadic = true
					if info.RequiredParams == len(d.Params) {
						info.RequiredParams = i
					}
				}

				if param.HasDefault && info.RequiredParams == len(d.Params) {
					info.RequiredParams = i
				}
			}

			g.tasks[d.Name.Name] = info

		case *ast.ConstDecl:
			g.consts[d.Name.Name] = g.inferExprType(d.Value, nil)
		}
	}
}

func (g *Generator) emitEnums(file *ast.File) {
	for _, decl := range file.Decls {
		d, ok := decl.(*ast.EnumDecl)
		if !ok {
			continue
		}

		g.linef("typedef enum %s {", d.Name.Name)
		g.indent++

		for i, variant := range d.Variants {
			comma := ","
			if i == len(d.Variants)-1 {
				comma = ""
			}

			g.linef("%s_%s%s", d.Name.Name, variant.Name, comma)
		}

		g.indent--
		g.linef("} %s;", d.Name.Name)
		g.line("")
	}
}

func (g *Generator) emitStructs(file *ast.File) {
	for _, decl := range file.Decls {
		d, ok := decl.(*ast.StructDecl)
		if !ok {
			continue
		}

		if len(d.Params) > 0 {
			g.error(d.Name.Span(), fmt.Sprintf("generic struct %q is not supported by C codegen yet", d.Name.Name))
			continue
		}

		g.linef("typedef struct %s {", d.Name.Name)
		g.indent++

		for _, field := range d.Fields {
			fieldType := g.cTypeFromAst(field.Type)
			g.linef("%s;", fieldType.Decl(field.Name.Name))
		}

		g.indent--
		g.linef("} %s;", d.Name.Name)
		g.line("")
	}
}

func (g *Generator) emitConstants(file *ast.File) {
	for _, decl := range file.Decls {
		d, ok := decl.(*ast.ConstDecl)
		if !ok {
			continue
		}

		typ := g.inferExprType(d.Value, nil)
		value := g.emitExpr(d.Value, &typ)
		g.linef("static const %s = %s;", typ.Decl(d.Name.Name), value)
	}

	if len(g.consts) > 0 {
		g.line("")
	}
}

func (g *Generator) emitImportedTaskPrototypes() {
	if len(g.packages) == 0 {
		return
	}

	names := make([]string, 0, len(g.packages))
	for name := range g.packages {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, pkgName := range names {
		pkg := g.packages[pkgName]
		if pkg == nil {
			continue
		}

		taskNames := make([]string, 0, len(pkg.Tasks))
		for taskName := range pkg.Tasks {
			taskNames = append(taskNames, taskName)
		}
		sort.Strings(taskNames)

		for _, taskName := range taskNames {
			info := pkg.Tasks[taskName]
			if taskName == "Main" {
				continue
			}

			g.linef("%s;", g.packageTaskSignature(pkgName, taskName, info))
		}
	}

	g.line("")
}

func (g *Generator) packageTaskSignature(packageName string, taskName string, info TaskInfo) string {
	name := cPackageTaskName(packageName, taskName)
	ret := info.ReturnType.Name

	if len(info.ParamTypes) == 0 {
		return fmt.Sprintf("%s %s(void)", ret, name)
	}

	var params []string
	for i, paramType := range info.ParamTypes {
		params = append(params, paramType.Decl(fmt.Sprintf("arg%d", i)))
	}

	return fmt.Sprintf("%s %s(%s)", ret, name, strings.Join(params, ", "))
}

func (g *Generator) emitTaskPrototypes(file *ast.File) {
	for _, decl := range file.Decls {
		d, ok := decl.(*ast.TaskDecl)
		if !ok || d.IsTest {
			continue
		}

		g.linef("%s;", g.taskSignature(d, false))
	}

	if len(g.tasks) > 0 {
		g.line("")
	}
}

func (g *Generator) emitTasks(file *ast.File) {
	for _, decl := range file.Decls {
		d, ok := decl.(*ast.TaskDecl)
		if !ok || d.IsTest {
			continue
		}

		info := g.tasks[d.Name.Name]
		if info.IsExtern {
			continue
		}

		g.emitTask(d)
		g.line("")
	}
}

func (g *Generator) emitTask(d *ast.TaskDecl) {
	info := g.tasks[d.Name.Name]

	g.currentTask = d
	g.currentResults = nil

	if len(d.Results) == 1 {
		g.currentResults = append(g.currentResults, g.cTypeFromAst(d.Results[0]))
	}

	g.linef("%s {", g.taskSignature(d, true))
	g.indent++

	oldScope := g.scope
	oldTaskScope := g.taskScope

	g.scope = newScope(oldScope)
	g.taskScope = g.scope

	for i, param := range d.Params {
		if i < len(info.ParamTypes) {
			paramType := info.ParamTypes[i]

			if i < len(info.ParamIsVariadic) && info.ParamIsVariadic[i] {
				paramType = g.variadicCType(paramType)
			}

			g.scope.declare(param.Name.Name, paramType)
		}
	}

	g.emitBlockStatements(d.Body)

	g.emitActiveDefers()

	if d.Name.Name == "Main" && len(d.Results) == 0 {
		g.line("return 0;")
	}

	g.scope = oldScope
	g.taskScope = oldTaskScope

	g.indent--
	g.line("}")

	g.currentTask = nil
	g.currentResults = nil
}

func (g *Generator) emitActiveDefers() {
	for sc := g.scope; sc != nil; sc = sc.parent {
		g.emitDefersInScope(sc)

		if sc == g.taskScope {
			break
		}
	}
}

func (g *Generator) emitDefersInScope(sc *scope) {
	for i := len(sc.defers) - 1; i >= 0; i-- {
		g.linef("%s;", sc.defers[i])
	}
}

func (g *Generator) taskSignature(d *ast.TaskDecl, definition bool) string {
	info := g.tasks[d.Name.Name]

	name := g.cTaskName(d.Name.Name)
	if info.IsExtern && info.ExternName != "" {
		name = info.ExternName
	}

	ret := info.ReturnType.Name

	if len(d.Params) == 0 {
		return fmt.Sprintf("%s %s(void)", ret, name)
	}

	var params []string

	for i, param := range d.Params {
		paramType := CInvalid
		if i < len(info.ParamTypes) {
			paramType = info.ParamTypes[i]
		}

		if i < len(info.ParamIsVariadic) && info.ParamIsVariadic[i] {
			if info.IsExtern {
				params = append(params, "...")
				break
			}

			params = append(params, g.variadicCType(paramType).Decl(param.Name.Name))
			break
		}

		params = append(params, paramType.Decl(param.Name.Name))
	}

	return fmt.Sprintf("%s %s(%s)", ret, name, strings.Join(params, ", "))
}

func (g *Generator) cTaskName(name string) string {
	if name == "Main" {
		return "main"
	}

	if g.packageName != "" {
		return sanitizeCName(g.packageName) + "_" + sanitizeCName(name)
	}

	return sanitizeCName(name)
}

func cPackageTaskName(packageName string, taskName string) string {
	return sanitizeCName(packageName) + "_" + sanitizeCName(taskName)
}

func sanitizeCName(name string) string {
	var b strings.Builder

	for _, ch := range name {
		if ch >= 'a' && ch <= 'z' ||
			ch >= 'A' && ch <= 'Z' ||
			ch >= '0' && ch <= '9' ||
			ch == '_' {
			b.WriteRune(ch)
			continue
		}

		b.WriteByte('_')
	}

	if b.Len() == 0 {
		return "_"
	}

	return b.String()
}

func (g *Generator) emitBlockStatements(block *ast.BlockStmt) {
	if block == nil {
		return
	}

	for _, stmt := range block.Stmts {
		g.emitStmt(stmt)
	}
}

func (g *Generator) emitStmt(stmt ast.Stmt) {
	switch s := stmt.(type) {
	case *ast.DeclStmt:
		g.error(s.Span(), "local declarations are not supported by C codegen yet")

	case *ast.BlockStmt:
		g.line("{")
		g.indent++

		oldScope := g.scope
		g.scope = newScope(oldScope)

		g.emitBlockStatements(s)
		g.emitDefersInScope(g.scope)

		g.scope = oldScope

		g.indent--
		g.line("}")

	case *ast.ReturnStmt:
		g.emitReturnStmt(s)

	case *ast.DeferStmt:
		g.emitDeferStmt(s)

	case *ast.SealStmt:
		// `seal` is a checker/language rule. It has no first-backend C output.

	case *ast.ExprStmt:
		g.linef("%s;", g.emitExpr(s.Expr, nil))

	case *ast.AssignStmt:
		leftType := g.inferExprType(s.Left, nil)
		left := g.emitExpr(s.Left, nil)
		right := g.emitExpr(s.Right, &leftType)
		g.linef("%s %s %s;", left, g.cAssignOp(s.Op), right)

	case *ast.VarDeclStmt:
		g.emitVarDeclStmt(s)

	case *ast.IfStmt:
		cond := g.emitExpr(s.Cond, &CBool)
		g.linef("if (%s) {", cond)
		g.indent++

		oldScope := g.scope
		g.scope = newScope(oldScope)
		g.emitBlockStatements(s.Then)
		g.emitDefersInScope(g.scope)
		g.scope = oldScope

		g.indent--

		if s.Else != nil {
			g.line("} else {")
			g.indent++

			oldScope := g.scope
			g.scope = newScope(oldScope)
			g.emitStmt(s.Else)
			g.emitDefersInScope(g.scope)
			g.scope = oldScope

			g.indent--
			g.line("}")
		} else {
			g.line("}")
		}

	case *ast.ForStmt:
		g.emitForStmt(s)

	case *ast.SwitchStmt:
		g.emitSwitchStmt(s)
	}
}

func (g *Generator) emitReturnStmt(s *ast.ReturnStmt) {
	if len(s.Values) == 0 {
		g.emitActiveDefers()

		if g.currentTask != nil && g.currentTask.Name.Name == "Main" {
			g.line("return 0;")
			return
		}

		g.line("return;")
		return
	}

	expected := (*CType)(nil)
	if len(g.currentResults) == 1 {
		expected = &g.currentResults[0]
	}

	resultTemp := g.newTemp("return_value")
	resultType := CInvalid
	if expected != nil {
		resultType = *expected
	} else {
		resultType = g.inferExprType(s.Values[0], nil)
	}

	g.linef("%s = %s;", resultType.Decl(resultTemp), g.emitExpr(s.Values[0], &resultType))
	g.emitActiveDefers()
	g.linef("return %s;", resultTemp)
}

func (g *Generator) emitVarDeclStmt(s *ast.VarDeclStmt) {
	var typ CType

	if s.HasType {
		typ = g.cTypeFromAst(s.Type)

		if typ.IsArray && typ.ArrayLen == "" && s.HasValue {
			if arr, ok := s.Value.(*ast.ArrayLiteralExpr); ok {
				typ.ArrayLen = fmt.Sprintf("%d", len(arr.Values))
			}
		}
	} else if s.HasValue {
		typ = g.inferExprType(s.Value, nil)
	} else {
		typ = CInvalid
	}

	g.scope.declare(s.Name.Name, typ)

	if s.HasValue {
		value := g.emitExpr(s.Value, &typ)

		if typ.IsArray {
			g.linef("%s = %s;", typ.Decl(s.Name.Name), value)
		} else {
			g.linef("%s = %s;", typ.Decl(s.Name.Name), value)
		}

		return
	}

	g.linef("%s;", typ.Decl(s.Name.Name))
}

func (g *Generator) emitForStmt(s *ast.ForStmt) {
	oldScope := g.scope
	g.scope = newScope(oldScope)

	if s.Init == nil && s.Cond == nil && s.Post == nil {
		g.line("for (;;) {")
		g.indent++
		g.emitBlockStatements(s.Body)
		g.emitDefersInScope(g.scope)
		g.indent--
		g.line("}")
		g.scope = oldScope
		return
	}

	if s.Init == nil && s.Post == nil {
		cond := g.emitExpr(s.Cond, &CBool)
		g.linef("for (; %s; ) {", cond)
		g.indent++
		g.emitBlockStatements(s.Body)
		g.emitDefersInScope(g.scope)
		g.indent--
		g.line("}")
		g.scope = oldScope
		return
	}

	init := ""
	if s.Init != nil {
		init = g.emitForPart(s.Init)
	}

	cond := ""
	if s.Cond != nil {
		cond = g.emitExpr(s.Cond, &CBool)
	}

	post := ""
	if s.Post != nil {
		post = g.emitForPart(s.Post)
	}

	g.linef("for (%s; %s; %s) {", init, cond, post)
	g.indent++
	g.emitBlockStatements(s.Body)
	g.emitDefersInScope(g.scope)
	g.indent--
	g.line("}")

	g.scope = oldScope
}

func (g *Generator) emitForPart(stmt ast.Stmt) string {
	switch s := stmt.(type) {
	case *ast.VarDeclStmt:
		var typ CType

		if s.HasType {
			typ = g.cTypeFromAst(s.Type)
		} else if s.HasValue {
			typ = g.inferExprType(s.Value, nil)
		} else {
			typ = CInvalid
		}

		g.scope.declare(s.Name.Name, typ)

		if s.HasValue {
			value := g.emitExpr(s.Value, &typ)
			return fmt.Sprintf("%s = %s", typ.Decl(s.Name.Name), value)
		}

		return typ.Decl(s.Name.Name)

	case *ast.AssignStmt:
		return fmt.Sprintf("%s %s %s", g.emitExpr(s.Left, nil), g.cAssignOp(s.Op), g.emitExpr(s.Right, nil))

	case *ast.ExprStmt:
		return g.emitExpr(s.Expr, nil)

	default:
		g.error(stmt.Span(), "unsupported for-loop component in C codegen")
		return ""
	}
}

func (g *Generator) emitSwitchStmt(s *ast.SwitchStmt) {
	if s.IsUnionSwitch {
		g.emitUnionSwitchStmt(s)
		return
	}

	targetType := g.inferExprType(s.Target, nil)
	target := g.emitExpr(s.Target, nil)

	g.linef("switch (%s) {", target)
	g.indent++

	for _, swCase := range s.Cases {
		switch swCase.Kind {
		case ast.SwitchCaseEnumVariant:
			g.linef("case %s_%s:", targetType.SealName, swCase.EnumVariant.Name)

		case ast.SwitchCaseDefault:
			g.line("default:")

		case ast.SwitchCaseExpr:
			g.linef("case %s:", g.emitExpr(swCase.Expr, &targetType))

		default:
			g.error(swCase.Loc, "unsupported switch case in C codegen")
			continue
		}

		g.indent++

		oldScope := g.scope
		g.scope = newScope(oldScope)

		for _, stmt := range swCase.Body {
			g.emitStmt(stmt)
		}

		g.emitDefersInScope(g.scope)
		g.line("break;")

		g.scope = oldScope

		g.indent--
	}

	g.indent--
	g.line("}")
}

func (g *Generator) emitUnionSwitchStmt(s *ast.SwitchStmt) {
	targetType := g.inferExprType(s.Target, nil)
	if !g.isUnion(targetType) {
		g.error(s.Target.Span(), fmt.Sprintf("union switch target is not a union: %s", targetType.String()))
		return
	}

	targetTemp := g.newTemp("union_switch")
	g.linef("%s = %s;", targetType.Decl(targetTemp), g.emitExpr(s.Target, &targetType))

	g.linef("switch (%s.tag) {", targetTemp)
	g.indent++

	for _, swCase := range s.Cases {
		switch swCase.Kind {
		case ast.SwitchCaseUnionMember:
			memberType := g.cTypeFromAst(swCase.UnionMember)
			g.linef("case %s_Tag_%s:", targetType.SealName, memberType.SealName)
			g.indent++
			g.line("{")
			g.indent++

			oldScope := g.scope
			g.scope = newScope(oldScope)

			if s.BindName.Name != "" {
				g.linef("%s = %s.as.%s;", memberType.Decl(s.BindName.Name), targetTemp, memberType.SealName)
				g.scope.declare(s.BindName.Name, memberType)
			}

			for _, stmt := range swCase.Body {
				g.emitStmt(stmt)
			}

			g.emitDefersInScope(g.scope)
			g.line("break;")

			g.scope = oldScope

			g.indent--
			g.line("}")
			g.indent--

		case ast.SwitchCaseNil:
			g.linef("case %s_Tag_nil:", targetType.SealName)
			g.indent++
			g.line("{")
			g.indent++

			oldScope := g.scope
			g.scope = newScope(oldScope)

			if s.BindName.Name != "" {
				g.linef("void *%s = NULL;", s.BindName.Name)
				g.scope.declare(s.BindName.Name, CNil)
			}

			for _, stmt := range swCase.Body {
				g.emitStmt(stmt)
			}

			g.emitDefersInScope(g.scope)
			g.line("break;")

			g.scope = oldScope

			g.indent--
			g.line("}")
			g.indent--

		case ast.SwitchCaseDefault:
			g.line("default:")
			g.indent++
			g.line("{")
			g.indent++

			oldScope := g.scope
			g.scope = newScope(oldScope)

			for _, stmt := range swCase.Body {
				g.emitStmt(stmt)
			}

			g.emitDefersInScope(g.scope)
			g.line("break;")

			g.scope = oldScope

			g.indent--
			g.line("}")
			g.indent--

		default:
			g.error(swCase.Loc, "unsupported union switch case in C codegen")
		}
	}

	g.indent--
	g.line("}")
}

func (g *Generator) emitExpr(expr ast.Expr, expected *CType) string {
	if expected != nil && expected.SealName == "any" {
		return g.emitAnyExpr(expr)
	}

	switch e := expr.(type) {
	case *ast.IdentExpr:
		if _, ok := g.scope.lookup(e.Name.Name); ok {
			return e.Name.Name
		}

		return e.Name.Name

	case *ast.DotIdentExpr:
		if expected != nil && expected.SealName != "" {
			if _, ok := g.enums[expected.SealName]; ok {
				return fmt.Sprintf("%s_%s", expected.SealName, e.Name.Name)
			}
		}

		g.error(e.Span(), fmt.Sprintf("enum literal .%s needs C codegen context", e.Name.Name))
		return "0"

	case *ast.IntLitExpr:
		return e.Value

	case *ast.FloatLitExpr:
		return e.Value

	case *ast.StringLitExpr:
		return e.Value

	case *ast.BoolLitExpr:
		if e.Value {
			return "true"
		}

		return "false"

	case *ast.NilLitExpr:
		if expected != nil && g.isUnion(*expected) {
			return fmt.Sprintf("(%s){.tag = %s_Tag_nil}", expected.Name, expected.SealName)
		}

		return "NULL"

	case *ast.UnaryExpr:
		return fmt.Sprintf("(%s%s)", g.cUnaryOp(e.Op), g.emitExpr(e.Expr, nil))

	case *ast.BinaryExpr:
		leftType := g.inferExprType(e.Left, nil)
		rightType := g.inferExprType(e.Right, nil)

		if g.hasOperatorOverload(e.Op.String()) {
			if candidate, ok := g.resolveOverload(e.Op.String(), []CType{leftType, rightType}); ok {
				left := g.emitExpr(e.Left, &leftType)
				right := g.emitExpr(e.Right, &rightType)
				return fmt.Sprintf("%s(%s, %s)", g.cTaskName(candidate), left, right)
			}
		}

		if e.Op == token.NotEq && g.hasOperatorOverload("==") {
			if candidate, ok := g.resolveOverload("==", []CType{leftType, rightType}); ok {
				left := g.emitExpr(e.Left, &leftType)
				right := g.emitExpr(e.Right, &rightType)
				return fmt.Sprintf("(!%s(%s, %s))", g.cTaskName(candidate), left, right)
			}
		}

		left := g.emitExpr(e.Left, nil)
		right := g.emitExpr(e.Right, nil)
		return fmt.Sprintf("(%s %s %s)", left, g.cBinaryOp(e.Op), right)

	case *ast.CallExpr:
		return g.emitCallExpr(e)

	case *ast.SelectorExpr:
		if id, ok := e.Left.(*ast.IdentExpr); ok {
			if _, ok := g.packages[id.Name.Name]; ok {
				// Package selector as value is only valid through calls for now.
				return cPackageTaskName(id.Name.Name, e.Name.Name)
			}
		}

		left := g.emitExpr(e.Left, nil)
		leftType := g.inferExprType(e.Left, nil)

		if strings.HasSuffix(leftType.SealName, "*") {
			return fmt.Sprintf("(%s)->%s", left, e.Name.Name)
		}

		if strings.HasPrefix(leftType.SealName, "*") {
			return fmt.Sprintf("(%s)->%s", left, e.Name.Name)
		}

		return fmt.Sprintf("(%s).%s", left, e.Name.Name)

	case *ast.IndexExpr:
		leftType := g.inferExprType(e.Left, nil)
		left := g.emitExpr(e.Left, nil)
		index := g.emitExpr(e.Index, &CInt)

		if leftType.IsVariadic {
			return fmt.Sprintf("(%s).data[%s]", left, index)
		}

		return fmt.Sprintf("%s[%s]", left, index)

	case *ast.ArrayLiteralExpr:
		var values []string

		elemExpected := (*CType)(nil)
		if expected != nil && expected.IsArray && expected.Elem != nil {
			elemExpected = expected.Elem
		}

		for _, value := range e.Values {
			values = append(values, g.emitExpr(value, elemExpected))
		}

		return "{" + strings.Join(values, ", ") + "}"

	case *ast.CompoundLiteralExpr:
		typ := g.cTypeFromAst(e.Type)

		if expected != nil && g.isUnion(*expected) && g.unionHasMember(expected.SealName, typ.SealName) {
			payload := g.emitCompoundLiteral(e, typ)
			return fmt.Sprintf("(%s){.tag = %s_Tag_%s, .as.%s = %s}",
				expected.Name,
				expected.SealName,
				typ.SealName,
				typ.SealName,
				payload,
			)
		}

		return g.emitCompoundLiteral(e, typ)
	}

	g.error(expr.Span(), "unsupported expression in C codegen")
	return "0"
}

func (g *Generator) emitAnyExpr(expr ast.Expr) string {
	srcType := g.inferExprType(expr, nil)

	if srcType.SealName == "any" {
		return g.emitExpr(expr, nil)
	}

	value := g.emitExpr(expr, &srcType)

	switch srcType.SealName {
	case "bool":
		return fmt.Sprintf("sealAny_bool(%s)", value)
	case "int":
		return fmt.Sprintf("sealAny_int(%s)", value)
	case "usize":
		return fmt.Sprintf("sealAny_usize(%s)", value)
	case "f32":
		return fmt.Sprintf("sealAny_f32(%s)", value)
	case "f64":
		return fmt.Sprintf("sealAny_f64(%s)", value)
	case "string":
		return fmt.Sprintf("sealAny_string(%s)", value)
	case "rawptr":
		return fmt.Sprintf("sealAny_rawptr(%s)", value)
	default:
		g.error(expr.Span(), fmt.Sprintf("cannot box %s as any yet", srcType.String()))
		return "sealAny_any((sealAny){0})"
	}
}

func (g *Generator) emitCallExpr(e *ast.CallExpr) string {
	return g.emitCallExprWithArgs(e, nil)
}

func (g *Generator) emitCallExprWithArgs(e *ast.CallExpr, preparedArgs []string) string {
	if id, ok := e.Callee.(*ast.IdentExpr); ok && id.Name.Name == "len" {
		return g.emitLenCall(e)
	}
	if id, ok := e.Callee.(*ast.IdentExpr); ok {
		if id.Name.Name == "Print" {
			return g.emitBuiltinPrintWithArgs(e, preparedArgs)
		}

		argTypes := make([]CType, 0, len(e.Args))
		for _, arg := range e.Args {
			argTypes = append(argTypes, g.inferExprType(arg, nil))
		}

		if _, isOverload := g.overloads[id.Name.Name]; isOverload {
			candidate, ok := g.resolveOverload(id.Name.Name, argTypes)
			if !ok {
				g.error(e.Span(), fmt.Sprintf("could not resolve overload %q in C codegen", id.Name.Name))
				return "0"
			}

			return g.emitTaskCall(candidate, e.Args, preparedArgs)
		}

		return g.emitTaskCall(id.Name.Name, e.Args, preparedArgs)
	}

	if selector, ok := e.Callee.(*ast.SelectorExpr); ok {
		if id, ok := selector.Left.(*ast.IdentExpr); ok {
			if pkg := g.packages[id.Name.Name]; pkg != nil {
				return g.emitPackageTaskCall(id.Name.Name, selector.Name.Name, e.Args, preparedArgs)
			}
		}
	}

	var args []string

	if preparedArgs != nil {
		args = append(args, preparedArgs...)
	} else {
		for _, arg := range e.Args {
			args = append(args, g.emitExpr(arg, nil))
		}
	}

	return fmt.Sprintf("%s(%s)", g.emitExpr(e.Callee, nil), strings.Join(args, ", "))
}

func (g *Generator) emitLenCall(e *ast.CallExpr) string {
	if len(e.Args) != 1 {
		g.error(e.Span(), "len expects 1 argument")
		return "0"
	}

	argType := g.inferExprType(e.Args[0], nil)
	arg := g.emitExpr(e.Args[0], nil)

	if argType.IsVariadic {
		return fmt.Sprintf("(int)((%s).len)", arg)
	}

	if argType.IsArray {
		return argType.ArrayLen
	}

	g.error(e.Args[0].Span(), fmt.Sprintf("len does not support %s", argType.String()))
	return "0"
}

func (g *Generator) emitTaskCall(taskName string, args []ast.Expr, preparedArgs []string) string {
	info, hasTask := g.tasks[taskName]

	name := g.cTaskName(taskName)
	if hasTask && info.IsExtern && info.ExternName != "" {
		name = info.ExternName
	}

	if hasTask && info.IsVariadic && !info.IsExtern {
		return g.emitSealVariadicTaskCall(name, info, args, preparedArgs)
	}

	var outArgs []string

	for i, arg := range args {
		if preparedArgs != nil && i < len(preparedArgs) {
			outArgs = append(outArgs, preparedArgs[i])
			continue
		}

		expected := (*CType)(nil)
		if hasTask && i < len(info.ParamTypes) {
			if i < len(info.ParamIsVariadic) && info.ParamIsVariadic[i] {
				expected = nil
			} else {
				expected = &info.ParamTypes[i]
			}
		}

		outArgs = append(outArgs, g.emitExpr(arg, expected))
	}

	if hasTask && !info.IsVariadic {
		for i := len(args); i < len(info.ParamTypes); i++ {
			if i < len(info.ParamHasDefault) && info.ParamHasDefault[i] {
				expected := info.ParamTypes[i]
				outArgs = append(outArgs, g.emitExpr(info.ParamDefaults[i], &expected))
			}
		}
	}

	return fmt.Sprintf("%s(%s)", name, strings.Join(outArgs, ", "))
}

func (g *Generator) emitSealVariadicTaskCall(name string, info TaskInfo, args []ast.Expr, preparedArgs []string) string {
	total := len(info.ParamTypes)
	fixedCount := total - 1

	var outArgs []string

	for i := 0; i < fixedCount && i < len(args); i++ {
		if preparedArgs != nil && i < len(preparedArgs) {
			outArgs = append(outArgs, preparedArgs[i])
			continue
		}

		expected := info.ParamTypes[i]
		outArgs = append(outArgs, g.emitExpr(args[i], &expected))
	}

	elemType := CInvalid
	if total > 0 {
		elemType = info.ParamTypes[total-1]
	}

	var rest []ast.Expr
	if len(args) > fixedCount {
		rest = args[fixedCount:]
	}

	outArgs = append(outArgs, g.emitVariadicLiteral(elemType, rest, preparedArgs, fixedCount))

	return fmt.Sprintf("%s(%s)", name, strings.Join(outArgs, ", "))
}

func (g *Generator) emitVariadicLiteral(elem CType, args []ast.Expr, preparedArgs []string, preparedOffset int) string {
	variadicType := g.variadicCType(elem)

	if len(args) == 0 {
		return fmt.Sprintf("(%s){.data = NULL, .len = 0}", variadicType.Name)
	}

	var values []string

	for i, arg := range args {
		globalIndex := preparedOffset + i

		if preparedArgs != nil && globalIndex < len(preparedArgs) {
			values = append(values, preparedArgs[globalIndex])
			continue
		}

		values = append(values, g.emitExpr(arg, &elem))
	}

	return fmt.Sprintf(
		"(%s){.data = (%s[]){%s}, .len = %d}",
		variadicType.Name,
		elem.Name,
		strings.Join(values, ", "),
		len(values),
	)
}

func (g *Generator) emitBuiltinPrint(e *ast.CallExpr) string {
	return g.emitBuiltinPrintWithArgs(e, nil)
}

func (g *Generator) emitBuiltinPrintWithArgs(e *ast.CallExpr, preparedArgs []string) string {
	if len(e.Args) == 0 {
		return `printf("")`
	}

	var format strings.Builder
	var args []string

	for i, arg := range e.Args {
		argType := g.inferExprType(arg, nil)

		rendered := ""
		if preparedArgs != nil && i < len(preparedArgs) {
			rendered = preparedArgs[i]
		} else {
			rendered = g.emitExpr(arg, nil)
		}

		switch argType.SealName {
		case "int":
			format.WriteString("%d")
			args = append(args, rendered)

		case "f32", "f64":
			format.WriteString("%f")
			args = append(args, rendered)

		case "bool":
			format.WriteString("%s")
			args = append(args, fmt.Sprintf("(%s ? \"true\" : \"false\")", rendered))

		case "string":
			format.WriteString("%s")
			args = append(args, rendered)

		default:
			g.error(arg.Span(), fmt.Sprintf("Print does not support %s in C codegen yet", argType.String()))
		}
	}

	if len(args) == 0 {
		return fmt.Sprintf("printf(\"%s\")", escapeCString(format.String()))
	}

	return fmt.Sprintf("printf(\"%s\", %s)", escapeCString(format.String()), strings.Join(args, ", "))
}

func (g *Generator) emitDeferStmt(s *ast.DeferStmt) {
	call, ok := s.Call.(*ast.CallExpr)
	if !ok {
		g.error(s.Span(), "defer currently supports only task calls")
		return
	}

	code := g.emitDeferredCall(call)
	g.scope.addDefer(code)
}

func (g *Generator) emitDeferredCall(call *ast.CallExpr) string {
	preparedArgs := make([]string, 0, len(call.Args))

	for _, arg := range call.Args {
		argType := g.inferExprType(arg, nil)
		temp := g.newTemp("defer_arg")

		g.linef("%s = %s;", argType.Decl(temp), g.emitExpr(arg, &argType))
		preparedArgs = append(preparedArgs, temp)
	}

	return g.emitCallExprWithArgs(call, preparedArgs)
}

func (g *Generator) emitUnions(file *ast.File) {
	for _, decl := range file.Decls {
		d, ok := decl.(*ast.UnionDecl)
		if !ok {
			continue
		}

		if d.Raw {
			g.error(d.Name.Span(), "@rawUnion is not supported by this C codegen phase yet")
			continue
		}

		g.linef("typedef enum %s_Tag {", d.Name.Name)
		g.indent++
		g.linef("%s_Tag_nil = 0,", d.Name.Name)

		for i, member := range d.Members {
			memberType := g.cTypeFromAst(member)
			comma := ","
			if i == len(d.Members)-1 {
				comma = ""
			}

			g.linef("%s_Tag_%s%s", d.Name.Name, memberType.SealName, comma)
		}

		g.indent--
		g.linef("} %s_Tag;", d.Name.Name)
		g.line("")

		g.linef("typedef struct %s {", d.Name.Name)
		g.indent++
		g.linef("%s_Tag tag;", d.Name.Name)
		g.line("union {")
		g.indent++

		for _, member := range d.Members {
			memberType := g.cTypeFromAst(member)
			g.linef("%s;", memberType.Decl(memberType.SealName))
		}

		g.indent--
		g.line("} as;")
		g.indent--
		g.linef("} %s;", d.Name.Name)
		g.line("")
	}
}

func (g *Generator) emitPackageTaskCall(packageName string, taskName string, args []ast.Expr, preparedArgs []string) string {
	pkg := g.packages[packageName]
	if pkg == nil {
		g.error(argsSpan(args), fmt.Sprintf("unknown package %q", packageName))
		return "0"
	}

	info, hasTask := pkg.Tasks[taskName]
	if !hasTask {
		g.error(argsSpan(args), fmt.Sprintf("package %s has no task %q", packageName, taskName))
		return "0"
	}
	if info.IsVariadic && !info.IsExtern {
		return g.emitSealVariadicTaskCall(cPackageTaskName(packageName, taskName), info, args, preparedArgs)
	}

	var outArgs []string

	for i, arg := range args {
		if preparedArgs != nil && i < len(preparedArgs) {
			outArgs = append(outArgs, preparedArgs[i])
			continue
		}

		expected := (*CType)(nil)
		if i < len(info.ParamTypes) {
			expected = &info.ParamTypes[i]
		}

		outArgs = append(outArgs, g.emitExpr(arg, expected))
	}

	for i := len(args); i < len(info.ParamTypes); i++ {
		if i < len(info.ParamHasDefault) && info.ParamHasDefault[i] {
			expected := info.ParamTypes[i]
			outArgs = append(outArgs, g.emitExpr(info.ParamDefaults[i], &expected))
		}
	}

	return fmt.Sprintf("%s(%s)", cPackageTaskName(packageName, taskName), strings.Join(outArgs, ", "))
}

func (g *Generator) emitCompoundLiteral(e *ast.CompoundLiteralExpr, typ CType) string {
	var values []string

	for _, field := range e.Fields {
		fieldType := g.lookupStructFieldType(typ.SealName, field.Name.Name)
		values = append(values, fmt.Sprintf(".%s = %s", field.Name.Name, g.emitExpr(field.Value, &fieldType)))
	}

	for _, value := range e.Values {
		values = append(values, g.emitExpr(value, nil))
	}

	return fmt.Sprintf("(%s){%s}", typ.Name, strings.Join(values, ", "))
}

func (g *Generator) emitRuntimeSupport() {
	g.line("typedef enum sealTypeKind {")
	g.indent++
	g.line("sealType_invalid = 0,")
	g.line("sealType_bool,")
	g.line("sealType_int,")
	g.line("sealType_usize,")
	g.line("sealType_f32,")
	g.line("sealType_f64,")
	g.line("sealType_string,")
	g.line("sealType_rawptr,")
	g.line("sealType_any")
	g.indent--
	g.line("} sealTypeKind;")
	g.line("")

	g.line("typedef struct sealAny {")
	g.indent++
	g.line("sealTypeKind type;")
	g.line("union {")
	g.indent++
	g.line("bool as_bool;")
	g.line("int as_int;")
	g.line("size_t as_usize;")
	g.line("float as_f32;")
	g.line("double as_f64;")
	g.line("const char *as_string;")
	g.line("void *as_rawptr;")
	g.indent--
	g.line("} value;")
	g.indent--
	g.line("} sealAny;")
	g.line("")

	g.line("static inline sealAny sealAny_bool(bool value) { sealAny out; out.type = sealType_bool; out.value.as_bool = value; return out; }")
	g.line("static inline sealAny sealAny_int(int value) { sealAny out; out.type = sealType_int; out.value.as_int = value; return out; }")
	g.line("static inline sealAny sealAny_usize(size_t value) { sealAny out; out.type = sealType_usize; out.value.as_usize = value; return out; }")
	g.line("static inline sealAny sealAny_f32(float value) { sealAny out; out.type = sealType_f32; out.value.as_f32 = value; return out; }")
	g.line("static inline sealAny sealAny_f64(double value) { sealAny out; out.type = sealType_f64; out.value.as_f64 = value; return out; }")
	g.line("static inline sealAny sealAny_string(const char *value) { sealAny out; out.type = sealType_string; out.value.as_string = value; return out; }")
	g.line("static inline sealAny sealAny_rawptr(void *value) { sealAny out; out.type = sealType_rawptr; out.value.as_rawptr = value; return out; }")
	g.line("static inline sealAny sealAny_any(sealAny value) { return value; }")
	g.line("")

	g.emitVariadicRuntimeType(CBool)
	g.emitVariadicRuntimeType(CInt)
	g.emitVariadicRuntimeType(CUsize)
	g.emitVariadicRuntimeType(CF32)
	g.emitVariadicRuntimeType(CF64)
	g.emitVariadicRuntimeType(CString)
	g.emitVariadicRuntimeType(CRawptr)
	g.emitVariadicRuntimeType(CAny)
	g.line("")
}

func (g *Generator) emitVariadicRuntimeType(elem CType) {
	name := g.variadicCType(elem).Name
	g.linef("typedef struct %s {", name)
	g.indent++
	g.linef("%s *data;", elem.Name)
	g.line("size_t len;")
	g.indent--
	g.linef("} %s;", name)
}

func (g *Generator) variadicCType(elem CType) CType {
	name := "sealVariadic_" + sanitizeCName(elem.SealName)

	return CType{
		Name:       name,
		SealName:   "..." + elem.SealName,
		IsVariadic: true,
		Elem:       &elem,
	}
}

func (g *Generator) emitCImports(file *ast.File) {
	emitted := false

	for _, decl := range file.Decls {
		d, ok := decl.(*ast.DirectiveDecl)
		if !ok {
			continue
		}

		if d.Directive.Name != "c_import" {
			continue
		}

		for i := 0; i < len(d.Body); i++ {
			tok := d.Body[i]

			if tok.Kind == token.Ident && tok.Lexeme == "include" {
				if i+1 >= len(d.Body) || d.Body[i+1].Kind != token.StringLit {
					g.error(tok.Span, "expected string literal after include in @c_import")
					continue
				}

				g.linef("#include %s", d.Body[i+1].Lexeme)
				emitted = true
				i++
				continue
			}

			if tok.Kind == token.Ident {
				g.error(tok.Span, fmt.Sprintf("unsupported @c_import directive item %q", tok.Lexeme))
			}
		}
	}

	if emitted {
		g.line("")
	}
}

func argsSpan(args []ast.Expr) source.Span {
	if len(args) == 0 {
		return source.Span{}
	}

	return args[0].Span()
}

func (g *Generator) inferExprType(expr ast.Expr, expected *CType) CType {
	switch e := expr.(type) {
	case *ast.IdentExpr:
		if v, ok := g.scope.lookup(e.Name.Name); ok {
			return v.Type
		}

		if typ, ok := g.consts[e.Name.Name]; ok {
			return typ
		}

		if info, ok := g.tasks[e.Name.Name]; ok {
			return info.ReturnType
		}

		return CInvalid

	case *ast.DotIdentExpr:
		if expected != nil {
			return *expected
		}

		return CInvalid

	case *ast.IntLitExpr:
		return CInt

	case *ast.FloatLitExpr:
		if expected != nil && expected.SealName == "f32" {
			return CF32
		}

		return CF64

	case *ast.StringLitExpr:
		return CString

	case *ast.BoolLitExpr:
		return CBool

	case *ast.NilLitExpr:
		if expected != nil {
			return *expected
		}

		return CNil

	case *ast.UnaryExpr:
		inner := g.inferExprType(e.Expr, nil)

		switch e.Op {
		case token.Amp:
			return CType{
				Name:     inner.Name + " *",
				SealName: "*" + inner.SealName,
			}

		case token.Star:
			if strings.HasPrefix(inner.SealName, "*") {
				return CType{
					Name:     strings.TrimSuffix(strings.TrimSpace(inner.Name), "*"),
					SealName: strings.TrimPrefix(inner.SealName, "*"),
				}
			}
		}

		return inner

	case *ast.BinaryExpr:
		left := g.inferExprType(e.Left, nil)
		right := g.inferExprType(e.Right, nil)

		if g.hasOperatorOverload(e.Op.String()) {
			if candidate, ok := g.resolveOverload(e.Op.String(), []CType{left, right}); ok {
				info := g.tasks[candidate]
				return info.ReturnType
			}
		}

		if e.Op == token.NotEq && g.hasOperatorOverload("==") {
			if _, ok := g.resolveOverload("==", []CType{left, right}); ok {
				return CBool
			}
		}

		switch e.Op {
		case token.EqEq,
			token.NotEq,
			token.Lt,
			token.LtEq,
			token.Gt,
			token.GtEq,
			token.AndAnd,
			token.OrOr:
			return CBool
		}

		if left.SealName == "f64" || right.SealName == "f64" {
			return CF64
		}

		if left.SealName == "f32" || right.SealName == "f32" {
			return CF32
		}

		return left

	case *ast.CallExpr:
		if id, ok := e.Callee.(*ast.IdentExpr); ok && id.Name.Name == "len" {
			return CInt
		}

		if id, ok := e.Callee.(*ast.IdentExpr); ok {
			if id.Name.Name == "Print" {
				return CVoid
			}

			if info, ok := g.tasks[id.Name.Name]; ok {
				return info.ReturnType
			}

			if _, ok := g.overloads[id.Name.Name]; ok {
				argTypes := make([]CType, 0, len(e.Args))
				for _, arg := range e.Args {
					argTypes = append(argTypes, g.inferExprType(arg, nil))
				}

				candidate, ok := g.resolveOverload(id.Name.Name, argTypes)
				if !ok {
					return CInvalid
				}

				return g.tasks[candidate].ReturnType
			}
		}

		if selector, ok := e.Callee.(*ast.SelectorExpr); ok {
			if id, ok := selector.Left.(*ast.IdentExpr); ok {
				if pkg := g.packages[id.Name.Name]; pkg != nil {
					if info, ok := pkg.Tasks[selector.Name.Name]; ok {
						return info.ReturnType
					}
				}
			}
		}

		return CInvalid

	case *ast.SelectorExpr:
		if id, ok := e.Left.(*ast.IdentExpr); ok {
			if pkg := g.packages[id.Name.Name]; pkg != nil {
				if info, ok := pkg.Tasks[e.Name.Name]; ok {
					return info.ReturnType
				}
			}
		}

		leftType := g.inferExprType(e.Left, nil)
		sealName := strings.TrimPrefix(leftType.SealName, "*")
		return g.lookupStructFieldType(sealName, e.Name.Name)

	case *ast.IndexExpr:
		leftType := g.inferExprType(e.Left, nil)
		if (leftType.IsArray || leftType.IsVariadic) && leftType.Elem != nil {
			return *leftType.Elem
		}

		return CInvalid

	case *ast.ArrayLiteralExpr:
		elem := CInvalid

		if len(e.Values) > 0 {
			elem = g.inferExprType(e.Values[0], nil)
		}

		return CType{
			IsArray:  true,
			ArrayLen: fmt.Sprintf("%d", len(e.Values)),
			Elem:     &elem,
			Name:     elem.Name,
			SealName: "array",
		}

	case *ast.CompoundLiteralExpr:
		return g.cTypeFromAst(e.Type)
	}

	return CInvalid
}

func (g *Generator) resolveOverload(name string, argTypes []CType) (string, bool) {
	candidates := g.overloads[name]

	bestName := ""
	bestScore := 1 << 30
	ambiguous := false

	for _, candidate := range candidates {
		info, ok := g.tasks[candidate]
		if !ok {
			continue
		}

		score, ok := g.callScore(info, argTypes)
		if !ok {
			continue
		}

		if score < bestScore {
			bestName = candidate
			bestScore = score
			ambiguous = false
			continue
		}

		if score == bestScore {
			ambiguous = true
		}
	}

	if ambiguous {
		return "", false
	}

	if bestName == "" {
		return "", false
	}

	return bestName, true
}

func (g *Generator) callScore(info TaskInfo, argTypes []CType) (int, bool) {
	required := info.RequiredParams
	total := len(info.ParamTypes)

	if info.IsVariadic {
		fixedCount := total - 1

		if len(argTypes) < required {
			return 0, false
		}

		score := 0

		count := len(argTypes)
		if count > fixedCount {
			count = fixedCount
		}

		for i, argType := range argTypes[:count] {
			itemScore, ok := g.conversionScore(info.ParamTypes[i], argType)
			if !ok {
				return 0, false
			}

			score += itemScore
		}

		score += (len(argTypes) - count) * 20
		return score, true
	}

	if len(argTypes) < required || len(argTypes) > total {
		return 0, false
	}

	score := 0

	for i, argType := range argTypes {
		itemScore, ok := g.conversionScore(info.ParamTypes[i], argType)
		if !ok {
			return 0, false
		}

		score += itemScore
	}

	score += (total - len(argTypes)) * 5

	return score, true
}

func (g *Generator) conversionScore(dst CType, src CType) (int, bool) {
	if dst.SealName == src.SealName {
		return 0, true
	}

	if dst.SealName == "any" {
		return 20, true
	}

	if src.SealName == "int" && (dst.SealName == "f32" || dst.SealName == "f64") {
		return 2, true
	}

	if src.SealName == "f32" && dst.SealName == "f64" {
		return 2, true
	}

	if g.isUnion(dst) {
		if src.SealName == "nil" || g.unionHasMember(dst.SealName, src.SealName) {
			return 1, true
		}
	}

	if src.SealName == "nil" && strings.HasPrefix(dst.SealName, "*") {
		return 1, true
	}

	return 0, false
}

func (g *Generator) isUnion(t CType) bool {
	_, ok := g.unions[t.SealName]
	return ok
}

func (g *Generator) unionHasMember(unionName string, memberName string) bool {
	u := g.unions[unionName]
	if u == nil {
		return false
	}

	for _, member := range u.Members {
		memberType := g.cTypeFromAst(member)
		if memberType.SealName == memberName {
			return true
		}
	}

	return false
}

func (g *Generator) hasOperatorOverload(name string) bool {
	if !isOperatorName(name) {
		return false
	}

	_, ok := g.overloads[name]
	return ok
}

func isOperatorName(name string) bool {
	switch name {
	case "+", "-", "*", "/", "%", "==", "!=", "<", ">", "<=", ">=", "&", "|", "^":
		return true
	default:
		return false
	}
}

func (g *Generator) cTypeFromAst(t ast.Type) CType {
	switch typ := t.(type) {
	case *ast.NamedType:
		if len(typ.Parts) == 0 {
			return CInvalid
		}

		name := typ.Parts[len(typ.Parts)-1].Name

		switch name {
		case "void":
			return CVoid
		case "bool":
			return CBool
		case "int":
			return CInt
		case "usize":
			return CUsize
		case "rawptr":
			return CRawptr
		case "any":
			return CAny
		case "f32":
			return CF32
		case "f64":
			return CF64
		case "string":
			return CString
		default:
			return CType{Name: name, SealName: name}
		}

	case *ast.PointerType:
		elem := g.cTypeFromAst(typ.Elem)

		return CType{
			Name:     elem.Name + " *",
			SealName: "*" + elem.SealName,
		}

	case *ast.ArrayType:
		elem := g.cTypeFromAst(typ.Elem)
		length := ""

		if typ.Inferred {
			length = ""
		} else if typ.Len != nil {
			if lit, ok := typ.Len.(*ast.IntLitExpr); ok {
				length = lit.Value
			} else {
				length = g.emitExpr(typ.Len, &CInt)
			}
		}

		return CType{
			IsArray:  true,
			ArrayLen: length,
			Elem:     &elem,
			Name:     elem.Name,
			SealName: "[" + length + "]" + elem.SealName,
		}

	case *ast.GenericType:
		g.error(typ.Span(), "generic type instantiation is not supported by C codegen yet")
		return g.cTypeFromAst(typ.Base)
	}

	return CInvalid
}

func (g *Generator) cAssignOp(op token.Kind) string {
	switch op {
	case token.Assign:
		return "="
	case token.PlusEq:
		return "+="
	case token.MinusEq:
		return "-="
	case token.StarEq:
		return "*="
	case token.SlashEq:
		return "/="
	case token.PercentEq:
		return "%="
	default:
		return "="
	}
}

func (g *Generator) cUnaryOp(op token.Kind) string {
	switch op {
	case token.Minus:
		return "-"
	case token.Bang:
		return "!"
	case token.Tilde:
		return "~"
	case token.Amp:
		return "&"
	case token.Star:
		return "*"
	default:
		return ""
	}
}

func (g *Generator) cBinaryOp(op token.Kind) string {
	switch op {
	case token.Plus:
		return "+"
	case token.Minus:
		return "-"
	case token.Star:
		return "*"
	case token.Slash:
		return "/"
	case token.Percent:
		return "%"
	case token.EqEq:
		return "=="
	case token.NotEq:
		return "!="
	case token.Lt:
		return "<"
	case token.LtEq:
		return "<="
	case token.Gt:
		return ">"
	case token.GtEq:
		return ">="
	case token.AndAnd:
		return "&&"
	case token.OrOr:
		return "||"
	case token.Amp:
		return "&"
	case token.Pipe:
		return "|"
	case token.Caret:
		return "^"
	default:
		return "/*op*/"
	}
}

func (g *Generator) lookupStructFieldType(structName string, fieldName string) CType {
	d := g.structs[structName]
	if d == nil {
		return CInvalid
	}

	for _, field := range d.Fields {
		if field.Name.Name == fieldName {
			return g.cTypeFromAst(field.Type)
		}
	}

	return CInvalid
}

func (g *Generator) line(s string) {
	g.out.WriteString(strings.Repeat("\t", g.indent))
	g.out.WriteString(s)
	g.out.WriteByte('\n')
}

func (g *Generator) linef(format string, args ...any) {
	g.line(fmt.Sprintf(format, args...))
}

func (g *Generator) error(span source.Span, message string) {
	g.diags.Add(span, message)
}

func escapeCString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	return s
}
