[package]
name = "simdExample"
version = "0.2.0"
kind = "executable"
dependencies = [
    "vector",
    "lists",
    "mem",
    "fmt",
]

[build]
compiler = "cc"

[compiler.default]
standard = "c11"
c_flags = [
    "-Wall",
    "-Wextra",
]

[compiler.tcc]
path = "tcc"
c_flags = []
link_flags = []

[compiler.gcc]
c_flags = [
    "-O3",
    "-Wall",
    "-Wextra",
    "-Wpedantic",
]
link_flags = []

[compiler.clang]
c_flags = [
    "-O3",
    "-Wall",
    "-Wextra",
]
link_flags = []

[compiler.msvc]
c_flags = [
    "/O2",
]
link_flags = []
