[package]
name = "threadExample"
version = "0.2.0"
kind = "executable"
dependencies = [
    "thread",
    "threadNative",
    "sync",
    "atomic",
    "concurrent",
    "fmt",
]

[build]
compiler = "cc"

[compiler.default]
standard = "c11"
c_flags = [
    "-Wall",
    "-Wextra",
]

[compiler.tcc]
path = "tcc"
c_flags = []
link_flags = []

[compiler.gcc]
c_flags = [
    "-Wall",
    "-Wextra",
    "-Wpedantic",
]
link_flags = []

[compiler.clang]
c_flags = [
    "-Wall",
    "-Wextra",
]
link_flags = []

[compiler.msvc]
c_flags = []
link_flags = []
