[package]
name = "osExample"
version = "0.1.1"
kind = "executable"
dependencies = [
    "os",
    "fmt",
    "strings",
    "mem",
    "io",
]

[build]
compiler = "cc"

[compiler.default]
standard = "c11"
c_flags = [
    "-Wall",
    "-Wextra",
]

[compiler.gcc]
c_flags = [
    "-Wall",
    "-Wextra",
    "-Wpedantic",
]

[compiler.clang]
c_flags = [
    "-Wall",
    "-Wextra",
    "-Wconversion",
]
